#+TITLE: 2月5日 素材积累


* “物质时代”，人生取向不能跑偏
** 概括
1. 关注自己真实的生命，不要让物质损害生命，珍惜平凡的生活
2. 发展自己的智力，拥有好奇心和独立思考能力
3. 成为情感丰富的人，认识自己

** 摘抄
人的一生中最值得追求的目标是什么？我觉得是两样东西：一个是幸福，一个是优秀。幸福主要是生命的状态，一个人活的单纯就幸福，所以应该保护你生命的单纯；优秀是精神的状态，一个人有自己的头脑、有丰富的心灵、有高贵的灵魂，精神上就优秀。

欲望超过生命本身的需要，是痛苦的根源。其实，生命本身的需要和物质的欲望是两码事，现在我们往往把两者混淆起来。

** 评析
生命本身的需要在自然界和人际交往，它们都应该是属于自然的，
自然的需要也是比较容易满足的。但物质的欲望是社会刺激出来的，
也是永远不会有满足的。它们相比生命本身来说只是表面上的东西，
不应该花大力气去追求。

但我觉得这点很难。文章里所说的“欲望本身超过生命本身的需要，是痛苦的根源”
我不认同。痛苦的根源应该还是欲望无法满足。物质的欲望是社会刺激出来的，
但社会刺激出来的原因还是为了满足人际交往的欲望。
因为希望能和其他人保持更好的关系，所以才会追求名利。
所以名利这类物质的欲望与生命本身的需要并没有孰优孰劣之分，
错误的地方在于，名利是很难追求到的，因为它们是靠和人比较得来的，
而就算得到了名利，也不一定会得到自己本来希望的结果。
需要知道的是自己追求名利是为了追求什么东西。

* 论简单的生活
** 概括
1. 在满足肉体需要的基础上，重视精神需要
2. 安于简单而自由的生活

* 孤独的价值
** 概括
1. 孤独是必要、有价值的
2. 孤独能帮助人感受内在，获得心理健康
3. 孤独能激发人的艺术创造力和潜能

** 摘抄
从心理学的观点看，人之需要独处，是为了进行内在的整合。所谓整合，就是把新的经验放到内在记忆中的某个恰当位置上。唯有经过这一整合的过程，外来的印象才能被自我所消化，自我也才能成为一个既独立又生长着的系统。所以，有无独处的能力，关系到一个人能否真正形成一个相对自足的内心世界，而这又会进而影响到他与外部世界的关系。斯托尔引用温尼考特的见解指出，那种缺乏独处能力的人只具有“虚假的自我”，因此只是顺从、而不是体验外部世界，世界对于他仅是某种必须适应的对象，而不是可以满足他的主观性的场所，这样的人生当然就没有意义。
